version: '3.8'
services:
  whisper-api:
    build: .
    image: whisper-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
    environment:
      - CONFIG_PATH=/app/config/config.yaml
    restart: unless-stopped 